### ISSUE TITLE
Errors when running train_mnist.py on CPU and GPU with python 2.7 and 3.6

### ISSUE THREAD

**Issue by jacketdembys** [viebboy/PyGOP#3]
Hi, I am unable to run train_mnist after following the related tutorial. In fact, after running the following command:
**python gop_tutorial1.py -m hemlgop -c cpu**

I get the following errors/outputs: 

Using TensorFlow backend.
Start progressive learning
-------------Layer 0 ---------------Block 0 ------------------
##### Iterative Randomized Search #####
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/retina/dembysj/.conda/envs/op-ann-2/lib/python2.7/site-packages/GOP/utility/gop_search.py", line 93, in <module>
    main(sys.argv[1:])
  File "/home/retina/dembysj/.conda/envs/op-ann-2/lib/python2.7/site-packages/GOP/utility/gop_search.py", line 42, in main
    params = dill.load(f)
  File "/home/retina/dembysj/.conda/envs/op-ann-2/lib/python2.7/site-packages/dill/_dill.py", line 278, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/home/retina/dembysj/.conda/envs/op-ann-2/lib/python2.7/site-packages/dill/_dill.py", line 481, in load
    obj = StockUnpickler.load(self)
  File "/home/retina/dembysj/.conda/envs/op-ann-2/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/home/retina/dembysj/.conda/envs/op-ann-2/lib/python2.7/pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 3
Traceback (most recent call last):
  File "train_mnist.py", line 171, in <module>
    main(sys.argv[1:])
  File "train_mnist.py", line 157, in main
    verbose=True)
  File "/home/retina/dembysj/.conda/envs/op-ann-2/lib/python2.7/site-packages/GOP/models/hemlgop.py", line 152, in fit
    verbose)
  File "/home/retina/dembysj/.conda/envs/op-ann-2/lib/python2.7/site-packages/GOP/models/hemlgop.py", line 232, in progressive_learn
    test_data)
  File "/home/retina/dembysj/.conda/envs/op-ann-2/lib/python2.7/site-packages/GOP/utility/gop_utils.py", line 639, in search_cpu
    raise RuntimeError('Search process using CPU terminated but no result exists!')
RuntimeError: Search process using CPU terminated but no result exists!

I get the similar errors using CPU or GPU with Python 2.7 and 3.6. Please, do you have any guidance?
**I am using Ubuntu 16.04, TensorFlow 1.4.1 and Keras 2.2.4**

**Comment by Igallardo22** [comment]
Hi, 

Same problem with following versions:

- Ubuntu 20.04
- python 2.7 / 3.7 (tested on both)
- tensorflow 1.4.1 /  Keras 2.2.4
- Execution on CPU

**Comment by viebboy** [comment]
hi, 
If you look into the error message, you will see the line unsupported pickle protocol. This suggests that the code has been run on python3 and the intermediate result was created (using pickle from python 3) and when you run the code again, you run with python 2, without clearing the temporary directory.

I would suggest that if you run into trouble, try clearing the tmp_dir before running again the code. Please let me know if this fixes the issues

**Comment by gilsoneng** [comment]
@viebboy I had the same error running the code in python 3.6 ou 3.7
Should I run in python 2?

**Comment by viebboy** [comment]
@gilsoneng you should run the code using at least python 3.7

**Comment by gilsoneng** [comment]
Yes but I get the same error running on python 3.7
